Add category
Matthew-Abebe/Budget-Pal pull request #10
Opened 2021-06-02 22:25 UTC by Matthew-Abebe

![Screenshot (774)](https://user-images.githubusercontent.com/44979851/120559917-bb5f9600-c3b6-11eb-93ef-2806c5fc0952.png)
![Screenshot (776)](https://user-images.githubusercontent.com/44979851/120559920-be5a8680-c3b6-11eb-9ede-cd7f019796cf.png)
![Screenshot (775)](https://user-images.githubusercontent.com/44979851/120559929-c0bce080-c3b6-11eb-9ad1-922ecffb1bac.png)

2021-06-02 22:28 UTC, thebearingedge requested changes

2021-06-02 22:28 UTC, thebearingedge commented on client/pages/purchase-form.jsx
> +            <option value="Car">Car</option> */}
Please delete commented out code.

2021-06-02 22:28 UTC, thebearingedge commented on server/public/styles.css
> +  top: 25%;
you shouldn't need absolute positioning on this.

2021-06-02 22:33 UTC, Matthew-Abebe commented on server/public/styles.css
> +  top: 25%;
Is it okay if I use fixed?

2021-06-03 01:44 UTC, Matthew-Abebe commented
![Screenshot (778)](https://user-images.githubusercontent.com/44979851/120573512-90833b00-c3d2-11eb-995c-6f00b81c6268.png)
![Screenshot (779)](https://user-images.githubusercontent.com/44979851/120573524-9416c200-c3d2-11eb-8327-adf1803332d8.png)

2021-06-03 01:51 UTC, Matthew-Abebe commented
![Screenshot (781)](https://user-images.githubusercontent.com/44979851/120574083-7f86f980-c3d3-11eb-9ab1-fc6d4cbf9dcf.png)
![Screenshot (782)](https://user-images.githubusercontent.com/44979851/120574091-831a8080-c3d3-11eb-8f82-3e3085d9c3ca.png)

2021-06-03 16:58 UTC, thebearingedge approved these changes

2021-06-03 17:43 UTC, merged